### ISSUE TITLE
Twitter embeds seem to be not working.

### ISSUE THREAD

**Issue by drewsday** [sellorm/quarto-social-embeds#2]
Not that I'm surprised right now, given the dumpster fire that is twitter right now, but I tested all the examples from your example file, and the only one that didn't work was the twitter embed.  Here's my test page: https://drewsday.github.io/quartoblog/posts/hello/hello.html

**Comment by sellorm** [comment]
Thanks for raising this, Andrew.

Could you share your Quarto version so I can try to reproduce?

**Comment by drewsday** [comment]
I'm on 1.2.269.

**Comment by sellorm** [comment]
Thanks for raising this, Andrew.

As part of my own migration off of twitter and onto mastodon, I deleted all of my own tweets that were older than 30 days - including the one in the example!

So this problem is entirely of my own making. I've updated the examples on the website and in `example.qmd` to use a tweet that actually exists. 

Unfortunately, the service that Twitter makes available for tweet embedding isn't a "proper" API, so it's not easy to tell why it's not working without poking around in your browsers developer console. I've added another issue (#3) to track documentation improvements for this.

Apologies for the trouble, and thanks again for raising.
